"""CM-20 figures — phase-space flow from a Hamiltonian, and invariance along it.

Generates SVG figures into this `figures/` directory (plus captions.json) by
importing the module's own code in ../code. Run:  python3 make_figures.py
Convention shared by every module: matplotlib -> SVG (svg.fonttype='path' so the
text is portable vector outlines), saved next to a captions.json mapping each
filename to a short caption the browser renders under the figure.
"""
import json
import os
import sys

import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams["svg.fonttype"] = "path"      # text as vector paths (portable)
matplotlib.rcParams["font.size"] = 11
import matplotlib.pyplot as plt                    # noqa: E402
import numpy as np                                 # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "code"))
from poisson_brackets import (                     # noqa: E402
    poisson_bracket, time_derivative, is_canonical,
)

INK, FLOW, ALT, STEEL = "#3b3b6d", "#b5651d", "#9a5a8a", "#5a7d9a"

# the two coordinate observables, written as f(q, p)
Q_OBS = lambda q, p: q
P_OBS = lambda q, p: p


def _save(fig, name):
    fig.savefig(os.path.join(HERE, name), format="svg", bbox_inches="tight")
    plt.close(fig)


def main():
    caps = {}
    w = 1.4
    H = lambda q, p: 0.5 * p * p + 0.5 * w * w * q * q     # harmonic Hamiltonian

    # ---- Fig 1: Hamiltonian phase-space flow  qdot={q,H}, pdot={p,H} ---------
    qs = np.linspace(-2.4, 2.4, 21)
    ps = np.linspace(-3.2, 3.2, 21)
    U = np.zeros((ps.size, qs.size))
    V = np.zeros((ps.size, qs.size))
    for i, p in enumerate(ps):
        for j, q in enumerate(qs):
            U[i, j] = time_derivative(Q_OBS, H, q, p)        # {q,H} =  p
            V[i, j] = time_derivative(P_OBS, H, q, p)        # {p,H} = -w^2 q
    speed = np.hypot(U, V)

    fig, ax = plt.subplots(figsize=(6.2, 3.5))
    ax.streamplot(qs, ps, U, V, color=speed, cmap="cividis",
                  density=1.1, linewidth=0.9, arrowsize=0.9)
    qf = np.linspace(-2.4, 2.4, 220)
    pf = np.linspace(-3.2, 3.2, 220)
    QF, PF = np.meshgrid(qf, pf)
    HF = 0.5 * PF ** 2 + 0.5 * w * w * QF ** 2
    ax.contour(QF, PF, HF, levels=[0.4, 1.2, 2.4, 4.0],
               colors=[INK], linewidths=1.0, linestyles="--")
    pb = poisson_bracket(Q_OBS, P_OBS, 1.0, 1.0)             # = 1
    canon = is_canonical(Q_OBS, P_OBS, 1.0, 1.0)             # True
    ax.text(0.02, 0.04, f"$\\{{q,p\\}}={pb:.0f}$  (canonical: {canon})",
            transform=ax.transAxes, color=INK, fontsize=9)
    ax.set_xlabel("position $q$"); ax.set_ylabel("momentum $p$")
    ax.set_title(r"Hamiltonian flow  $\dot q=\{q,H\},\ \dot p=\{p,H\}$")
    _save(fig, "fig1_phase_flow.svg")
    caps["fig1_phase_flow.svg"] = (
        "Phase-space flow generated by the harmonic Hamiltonian H = p^2/2 + "
        "(1/2) w^2 q^2 (w=1.4). Streamlines are the Hamiltonian vector field "
        "(qdot, pdot) = ({q,H}, {p,H}) built from the module's time_derivative; "
        "dashed curves are constant-energy contours H = const, which the flow "
        "follows. The fundamental bracket {q,p}=1 makes the map canonical.")

    # ---- Fig 2: invariance along the flow -----------------------------------
    def rhs(q, p):
        return (time_derivative(Q_OBS, H, q, p),
                time_derivative(P_OBS, H, q, p))

    q, p = 2.0, 0.0
    dt, N = 0.01, 1800
    T = np.arange(N + 1) * dt
    qt = np.empty(N + 1); Et = np.empty(N + 1); brk = np.empty(N + 1)
    for n in range(N + 1):
        qt[n] = q
        Et[n] = H(q, p)
        brk[n] = poisson_bracket(H, H, q, p)                 # {H,H} = 0
        k1 = rhs(q, p)
        k2 = rhs(q + 0.5 * dt * k1[0], p + 0.5 * dt * k1[1])
        k3 = rhs(q + 0.5 * dt * k2[0], p + 0.5 * dt * k2[1])
        k4 = rhs(q + dt * k3[0], p + dt * k3[1])
        q += dt / 6.0 * (k1[0] + 2 * k2[0] + 2 * k3[0] + k4[0])
        p += dt / 6.0 * (k1[1] + 2 * k2[1] + 2 * k3[1] + k4[1])

    fig, ax = plt.subplots(figsize=(6.2, 3.5))
    ax.plot(T, qt, color=FLOW, lw=1.6, label=r"$q(t)$  (oscillates)")
    ax.plot(T, Et, color=INK, lw=2.2,
            label=r"$H(t)$  (invariant: $\{H,H\}=0$)")
    ax.axhline(Et[0], color="#aaaaaa", lw=0.6)
    ax.set_ylim(-2.6, 4.2)
    ax.set_xlabel("time $t$"); ax.set_ylabel("observable value")
    ax.set_title(r"Evolution by $\dot f=\{f,H\}$: energy conserved along the flow")
    ax.legend(loc="upper right", frameon=False)
    _save(fig, "fig2_invariance.svg")
    caps["fig2_invariance.svg"] = (
        "A single trajectory integrated with the bracket-defined velocity field "
        "fdot = {f,H}. The position q(t) (orange) oscillates, but the energy "
        "H(t) (blue) stays flat: it is invariant along the flow because "
        "{H,H} = 0. This is the equation of motion in Poisson-bracket form.")

    with open(os.path.join(HERE, "captions.json"), "w", encoding="utf-8") as fh:
        json.dump(caps, fh, indent=2)
    print("wrote", len(caps), "figures + captions.json to", HERE)


if __name__ == "__main__":
    main()
